# Generated by Django 4.2.16 on 2024-11-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20240707_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='builder_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='location_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='user_images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Navigation'},
        ),
        migrations.AddField(
            model_name='property',
            name='map_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='project_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='rera',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='video_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='community_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='community_image_url',
            field=models.ImageField(blank=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='hand_over',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
